# Form implementation generated from reading ui file 'res\designer\splash_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(340, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SplashScreen.sizePolicy().hasHeightForWidth())
        SplashScreen.setSizePolicy(sizePolicy)
        SplashScreen.setMinimumSize(QtCore.QSize(340, 350))
        self.centralwidget = QtWidgets.QWidget(parent=SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.circularProgressBarBase = QtWidgets.QFrame(parent=self.centralwidget)
        self.circularProgressBarBase.setGeometry(QtCore.QRect(10, 10, 320, 320))
        self.circularProgressBarBase.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.circularProgressBarBase.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circularProgressBarBase.setObjectName("circularProgressBarBase")
        self.circularProgress = QtWidgets.QFrame(parent=self.circularProgressBarBase)
        self.circularProgress.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularProgress.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(85, 85, 255, 0), stop:0.750 rgba(52, 152, 219, 255));\n"
"}")
        self.circularProgress.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.circularProgress.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circularProgress.setObjectName("circularProgress")
        self.circularBg = QtWidgets.QFrame(parent=self.circularProgressBarBase)
        self.circularBg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularBg.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: rgba(44, 62, 80, 150);\n"
"}")
        self.circularBg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.circularBg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circularBg.setObjectName("circularBg")
        self.container = QtWidgets.QFrame(parent=self.circularProgressBarBase)
        self.container.setGeometry(QtCore.QRect(20, 20, 280, 280))
        self.container.setStyleSheet("QFrame{\n"
"    border-radius: 140px;\n"
"    background-color: rgb(43, 43, 79);\n"
"}")
        self.container.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.container.setObjectName("container")
        self.loadingText = QtWidgets.QLabel(parent=self.container)
        self.loadingText.setGeometry(QtCore.QRect(65, 62, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.loadingText.setFont(font)
        self.loadingText.setStyleSheet("color: white;")
        self.loadingText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loadingText.setObjectName("loadingText")
        self.loadingPercentage = QtWidgets.QLabel(parent=self.container)
        self.loadingPercentage.setGeometry(QtCore.QRect(35, 95, 210, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(60)
        self.loadingPercentage.setFont(font)
        self.loadingPercentage.setStyleSheet("color: white;")
        self.loadingPercentage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loadingPercentage.setObjectName("loadingPercentage")
        self.loadingText_2 = QtWidgets.QLabel(parent=self.container)
        self.loadingText_2.setGeometry(QtCore.QRect(55, 175, 170, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.loadingText_2.setFont(font)
        self.loadingText_2.setStyleSheet("color: white;")
        self.loadingText_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loadingText_2.setWordWrap(True)
        self.loadingText_2.setObjectName("loadingText_2")
        self.loadingPercentage.raise_()
        self.loadingText_2.raise_()
        self.loadingText.raise_()
        self.circularBg.raise_()
        self.circularProgress.raise_()
        self.container.raise_()
        SplashScreen.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=SplashScreen)
        self.statusbar.setObjectName("statusbar")
        SplashScreen.setStatusBar(self.statusbar)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "Manga Panel Extractor"))
        self.loadingText.setText(_translate("SplashScreen", "LOADING"))
        self.loadingPercentage.setText(_translate("SplashScreen", "0%"))
        self.loadingText_2.setText(_translate("SplashScreen", "<html><head/><body><p>MANGA PANEL EXTRACTOR</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec())
